apiVersion: v1
kind: Service
metadata:
  name: __APP_NAME__-svc
  namespace: __NAMESPACE__
  labels:
    app: __APP_NAME__
spec:
  type: LoadBalancer
  selector:
    app: __APP_NAME__
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
